add gn->hvigor
Signed-off-by: qu-xianfei <quxianfei@huawei.com>

diff --git a/distributeddatamgr/relationalStoretest/relationalStoreStagetest/hvigorw b/distributeddatamgr/relationalStoretest/relationalStoreStagetest/hvigorw
--- a/distributeddatamgr/relationalStoretest/relationalStoreStagetest/hvigorw
+++ b/distributeddatamgr/relationalStoretest/relationalStoreStagetest/hvigorw
@@ -1,69 +1,61 @@
-@rem Copyright (C) 2023 Huawei Device Co., Ltd.
-@rem Licensed under the Apache License, Version 2.0 (the "License");
-@rem you may not use this file except in compliance with the License.
-@rem You may obtain a copy of the License at
-@rem
-@rem     http://www.apache.org/licenses/LICENSE-2.0
-@rem
-@rem Unless required by applicable law or agreed to in writing, software
-@rem distributed under the License is distributed on an "AS IS" BASIS,
-@rem WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-@rem See the License for the specific language governing permissions and
-@rem limitations under the License.
-@if "%DEBUG%" == "" @echo off
-@rem ##########################################################################
-@rem
-@rem  Hvigor startup script for Windows
-@rem
-@rem ##########################################################################
+# Copyright (c) 2023 Huawei Device Co., Ltd.
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
 
-@rem Set local scope for the variables with windows NT shell
-if "%OS%"=="Windows_NT" setlocal
+#!/bin/bash
 
-set DIRNAME=%~dp0
-if "%DIRNAME%" == "" set DIRNAME=.
-set APP_BASE_NAME=%~n0
-set APP_HOME=%DIRNAME%
+# ----------------------------------------------------------------------------
+#  Hvigor startup script, version 1.0.0
+#
+#  Required ENV vars:
+#  ------------------
+#    NODE_HOME - location of a Node home dir
+#    or
+#    Add /usr/local/nodejs/bin to the PATH environment variable
+# ----------------------------------------------------------------------------
 
-@rem Resolve any "." and ".." in APP_HOME to make it shorter.
-for %%i in ("%APP_HOME%") do set APP_HOME=%%~fi
+HVIGOR_APP_HOME=$(dirname $(readlink -f $0))
+HVIGOR_WRAPPER_SCRIPT=${HVIGOR_APP_HOME}/hvigor/hvigor-wrapper.js
+warn() {
+	echo ""
+	echo -e "\033[1;33m`date '+[%Y-%m-%d %H:%M:%S]'`$@\033[0m"
+}
 
-set WRAPPER_MODULE_PATH=%APP_HOME%\hvigor\hvigor-wrapper.js
-set NODE_EXE=node.exe
+error() {
+	echo ""
+	echo -e "\033[1;31m`date '+[%Y-%m-%d %H:%M:%S]'`$@\033[0m"
+}
 
-goto start
+fail() {
+	error "$@"
+	exit 1
+}
 
-:start
-@rem Find node.exe
-if defined NODE_HOME goto findNodeFromNodeHome
+# Determine node to start hvigor wrapper script
+if [ -n "${NODE_HOME}" ];then
+   EXECUTABLE_NODE="${NODE_HOME}/bin/node"
+   if [ ! -x "$EXECUTABLE_NODE" ];then
+       fail "ERROR: NODE_HOME is set to an invalid directory,check $NODE_HOME\n\nPlease set NODE_HOME in your environment to the location where your nodejs installed"
+   fi
+else
+   EXECUTABLE_NODE="node"
+   which ${EXECUTABLE_NODE} > /dev/null 2>&1 || fail "ERROR: NODE_HOME is not set and not 'node' command found in your path"
+fi
 
-%NODE_EXE% --version >NUL 2>&1
-if "%ERRORLEVEL%" == "0" goto execute
+# Check hvigor wrapper script
+if [ ! -r "$HVIGOR_WRAPPER_SCRIPT" ];then
+	fail "ERROR: Couldn't find hvigor/hvigor-wrapper.js in ${HVIGOR_APP_HOME}"
+fi
 
-echo.
-echo ERROR: NODE_HOME is not set and no 'node' command could be found in your PATH.
-echo.
-echo Please set the NODE_HOME variable in your environment to match the
-echo location of your NodeJs installation.
-
-goto fail
-
-:findNodeFromNodeHome
-set NODE_HOME=%NODE_HOME:"=%
-set NODE_EXE_PATH=%NODE_HOME%/%NODE_EXE%
-
-if exist "%NODE_EXE_PATH%" goto execute
-echo.
-echo ERROR: NODE_HOME is not set and no 'node' command could be found in your PATH.
-echo.
-echo Please set the NODE_HOME variable in your environment to match the
-echo location of your NodeJs installation.
-
-goto fail
-
-:execute
-@rem Execute hvigor
-"%NODE_EXE%" %WRAPPER_MODULE_PATH% %*
-
-:fail
-exit /b 1
+# start hvigor-wrapper script
+exec "${EXECUTABLE_NODE}" \
+	"${HVIGOR_WRAPPER_SCRIPT}" "$@"
